##  Data Manipulation and Analysis with Pandas

It is key task in any data science or data analysis project. Pandas provide a wide range of functions for data manipulation and analysis, making it clean, transform, and extract insights from data.

In [44]:
import pandas as pd
print("hi")

hi

In [45]:
df = pd.read_csv('dummy.csv')
df.head(5)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136

In [46]:
df.tail(5)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
23,24,62,183062.0,0,4,20,3811,43031.0,3.7,71.9,17876.0,184
24,25,45,88158.0,43,18,41,1542,8575.0,5.0,63.9,11219.0,668
25,26,19,173107.0,48,19,41,4687,75474.0,2.0,86.0,43523.0,994
26,27,18,32345.0,19,8,9,2928,28928.0,1.6,74.9,7063.0,512
27,28,39,187439.0,66,0,46,3403,64395.0,3.8,64.7,31347.0,728

In [47]:
df.describe()

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
count,28.000000,28.000000,27.000000,28.000000,28.000000,28.000000,28.000000,25.000000,28.000000,28.000000,26.000000,28.000000
mean,14.500000,38.785714,134492.592593,50.678571,8.750000,29.964286,2665.392857,50561.720000,2.885714,78.689286,22175.500000,443.785714
std,8.225975,14.237033,54029.313449,29.329613,6.162161,14.594474,1407.677555,27027.649251,1.228885,11.998776,15492.395578,244.300416
min,1.000000,18.000000,32345.000000,0.000000,0.000000,2.000000,125.000000,2619.000000,1.000000,60.300000,1226.000000,124.000000
25%,7.750000,29.000000,96039.500000,23.750000,4.000000,19.000000,1537.500000,28346.000000,1.950000,71.725000,6582.250000,238.500000
50%,14.500000,38.500000,158227.000000,50.000000,7.500000,32.000000,2844.500000,45514.000000,2.700000,75.550000,18135.500000,413.500000
75%,21.250000,47.250000,179729.500000,69.500000,14.250000,42.000000,3770.500000,73300.000000,3.875000,92.000000,37819.250000,635.750000
max,28.000000,63.000000,193688.000000,98.000000,19.000000,50.000000,5000.000000,94441.000000,5.000000,98.900000,47349.000000,994.000000

In [48]:
df.dtypes

id                      int64
age                     int64
salary                float64
score                   int64
experience_years        int64
projects_completed      int64
customer_count          int64
monthly_sales         float64
rating                float64
attendance_percent    float64
bonus                 float64
department_code         int64
dtype: object

In [49]:
## Handling missing value
df.isnull()

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,True,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,True,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False

In [50]:
df.isnull().any(axis=1)  # it means row wise tell where data is missing

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7      True
8     False
9     False
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18     True
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
dtype: bool

In [51]:
df.isnull().any() #it will tell which column has missing value

id                    False
age                   False
salary                 True
score                 False
experience_years      False
projects_completed    False
customer_count        False
monthly_sales          True
rating                False
attendance_percent    False
bonus                  True
department_code       False
dtype: bool

In [52]:
df.isnull().sum() #is telling which column has how many missing value

id                    0
age                   0
salary                1
score                 0
experience_years      0
projects_completed    0
customer_count        0
monthly_sales         3
rating                0
attendance_percent    0
bonus                 2
department_code       0
dtype: int64

In [53]:
df_filled = df.fillna(0) #replace all the missing value with 0
df_filled

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625
1,2,30,113141.0,68,18,45,3169,0.0,3.0,64.0,4385.0,482
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434
4,5,43,50401.0,44,4,5,5000,0.0,1.8,79.3,40867.0,136
5,6,43,182840.0,20,14,30,444,44345.0,4.7,71.2,6367.0,187
6,7,31,187936.0,41,7,45,2086,86275.0,1.7,60.3,16880.0,149
7,8,56,193688.0,98,11,34,699,45514.0,4.3,61.6,0.0,277
8,9,39,103921.0,94,0,23,2697,62758.0,4.5,93.7,6177.0,340
9,10,63,180411.0,53,7,12,4419,94106.0,1.1,98.9,38504.0,124
10,11,33,170562.0,33,15,28,1524,2619.0,4.9,94.4,6422.0,240
11,12,23,161882.0,24,1,16,1454,47253.0,1.8,71.9,39272.0,172
12,13,63,124533.0,90,4,37,2761,26646.0,1.7,76.2,31279.0,786
13,14,26,37582.0,22,15,45,2227,62049.0,2.8,87.5,0.0,526
14,15,32,81636.0,97,1,38,1973,20215.0,1.0,96.4,9108.0,259
15,16,18,148839.0,23,10,50,555,88195.0,3.3,72.4,35417.0,421
16,17,22,69408.0,9,18,49,3628,32850.0,2.6,78.8,20144.0,234
17,18,51,104776.0,1,7,2,3757,44061.0,2.1,94.2,17847.0,623
18,19,60,0.0,58,6,11,3147,22960.0,2.0,73.7,47349.0,681
19,20,46,140708.0,69,2,33,3643,79705.0,3.0,72.9,6280.0,357
20,21,40,184741.0,42,8,31,2299,25185.0,2.2,64.5,40311.0,807
21,22,20,177588.0,82,11,32,496,0.0,4.7,93.2,1226.0,406
22,23,53,175946.0,52,4,31,3972,62817.0,4.1,78.6,35765.0,294
23,24,62,183062.0,0,4,20,3811,43031.0,3.7,71.9,17876.0,184
24,25,45,88158.0,43,18,41,1542,8575.0,5.0,63.9,11219.0,668
25,26,19,173107.0,48,19,41,4687,75474.0,2.0,86.0,43523.0,994
26,27,18,32345.0,19,8,9,2928,28928.0,1.6,74.9,7063.0,512
27,28,39,187439.0,66,0,46,3403,64395.0,3.8,64.7,31347.0,728

In [54]:
## filling missing value with the mean of the column

df['sales_fillNA'] = df['monthly_sales'].fillna(df['monthly_sales'].mean())
df.head(10)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72
5,6,43,182840.0,20,14,30,444,44345.0,4.7,71.2,6367.0,187,44345.00
6,7,31,187936.0,41,7,45,2086,86275.0,1.7,60.3,16880.0,149,86275.00
7,8,56,193688.0,98,11,34,699,45514.0,4.3,61.6,NaN,277,45514.00
8,9,39,103921.0,94,0,23,2697,62758.0,4.5,93.7,6177.0,340,62758.00
9,10,63,180411.0,53,7,12,4419,94106.0,1.1,98.9,38504.0,124,94106.00

In [55]:
## Renaming columns
df = df.rename(columns={'salary':'CTC'})
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72

In [56]:
##Change dataTypes

df['Value_new'] = df['customer_count'].astype(float)
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00,3980.0
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72,3169.0
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00,4205.0
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00,125.0
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72,5000.0

In [57]:
df['monthly_sales_new'] = df['monthly_sales'].fillna(df['monthly_sales'].mean()).astype(int) ## first assigning missing value then changing its type
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00,3980.0,28346
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72,3169.0,50561
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00,4205.0,94441
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00,125.0,73300
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72,5000.0,50561

In [58]:
df['Increased CTC']=df['CTC'].apply(lambda x:(x+(x/10))) #created a new column with 10% increased CTC
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new,Increased CTC
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00,3980.0,28346,43312.5
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72,3169.0,50561,124455.1
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00,4205.0,94441,174049.7
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00,125.0,73300,196952.8
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72,5000.0,50561,55441.1

## Data Aggregating and Grouping

In [59]:
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new,Increased CTC
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00,3980.0,28346,43312.5
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72,3169.0,50561,124455.1
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00,4205.0,94441,174049.7
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00,125.0,73300,196952.8
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72,5000.0,50561,55441.1

In [60]:
# Group all them based on age and get mean of there project completed
grouped_mean = df.groupby('age')['projects_completed'].mean()
print(grouped_mean)

age
18    29.5
19    41.0
20    32.0
22    49.0
23    16.0
26    45.0
30    45.0
31    45.0
32    38.0
33    28.0
35    32.0
38    26.5
39    34.5
40    31.0
43    17.5
45    41.0
46    33.0
51     2.0
53    31.0
56    34.0
60    11.0
62    20.0
63    24.5
Name: projects_completed, dtype: float64

In [61]:
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new,Increased CTC
0,1,38,39375.0,66,5,46,3980,28346.0,3.3,74.0,2003.0,625,28346.00,3980.0,28346,43312.5
1,2,30,113141.0,68,18,45,3169,NaN,3.0,64.0,4385.0,482,50561.72,3169.0,50561,124455.1
2,3,38,158227.0,86,9,7,4205,94441.0,2.0,92.3,18395.0,780,94441.00,4205.0,94441,174049.7
3,4,35,179048.0,71,19,32,125,73300.0,2.1,91.9,41537.0,434,73300.00,125.0,73300,196952.8
4,5,43,50401.0,44,4,5,5000,NaN,1.8,79.3,40867.0,136,50561.72,5000.0,50561,55441.1

In [66]:
grouped_sum = df.groupby(['age', 'score'])['monthly_sales'].sum()
print(grouped_sum)

age  score
18   19       28928.0
     23       88195.0
19   48       75474.0
20   82           0.0
22   9        32850.0
23   24       47253.0
26   22       62049.0
30   68           0.0
31   41       86275.0
32   97       20215.0
33   33        2619.0
35   71       73300.0
38   66       28346.0
     86       94441.0
39   66       64395.0
     94       62758.0
40   42       25185.0
43   20       44345.0
     44           0.0
45   43        8575.0
46   69       79705.0
51   1        44061.0
53   52       62817.0
56   98       45514.0
60   58       22960.0
62   0        43031.0
63   53       94106.0
     90       26646.0
Name: monthly_sales, dtype: float64

In [67]:
## aggregate multiple function

grouped_agg = df.groupby('score')['age'].agg(['mean', 'sum', 'count'])
print(grouped_agg.head())

       mean  sum  count
score
0      62.0   62      1
1      51.0   51      1
9      22.0   22      1
19     18.0   18      1
20     43.0   43      1

## Merging and Joining Dataframes

In [75]:
df1 = pd.DataFrame({'key':['A','B','C'], 'value1':[1,2,3]})
df2 = pd.DataFrame({'key':['A','B','D'], 'value2':[4,5,6]})

In [76]:
df1

  key  value1
0   A       1
1   B       2
2   C       3

In [77]:
df2

  key  value2
0   A       4
1   B       5
2   D       6

In [78]:
## Merge dataFrame on the 'Key column'

pd.merge(df1,df2, on='key', how='inner') #merge on basis of key that intersect

  key  value1  value2
0   A       1       4
1   B       2       5

In [80]:
pd.merge(df1,df2, on='key', how='outer')

  key  value1  value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [81]:
pd.merge(df1,df2, on='key', how='left')

  key  value1  value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

In [84]:
pd.merge(df1,df2, on='key', how='right')

  key  value1  value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6