##  Data Manipulation and Analysis with Pandas

It is key task in any data science or data analysis project. Pandas provide a wide range of functions for data manipulation and analysis, making it clean, transform, and extract insights from data.

In [7]:
import pandas as pd
print("hi")

hi

In [8]:
df = pd.read_csv('dummy.csv')
df.head(5)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136

In [9]:
df.tail(5)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
44,45,60,179672,61,4,47,3078,39499.0,3.8,98.1,27758,343
45,46,40,95572,59,8,13,3863,10284.0,4.7,63.3,10412,940
46,47,53,120933,74,16,44,3637,45466.0,3.6,94.6,44178,166
47,48,34,113727,20,19,29,2842,79534.0,1.4,62.0,36665,818
48,49,57,138630,53,16,39,1058,73865.0,1.7,96.9,46362,252

In [10]:
df.describe()

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
count,49.00000,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000,46.000000,49.000000,49.000000,49.000000,49.000000
mean,25.00000,40.755102,132389.693878,50.816327,9.306122,28.387755,2736.877551,53354.804348,3.106122,78.736735,24147.734694,507.142857
std,14.28869,13.795426,48646.334840,25.863966,6.305434,14.987239,1462.901122,28818.937261,1.236495,12.449627,15395.004820,272.097639
min,1.00000,18.000000,32345.000000,0.000000,0.000000,1.000000,29.000000,2619.000000,1.000000,60.300000,1226.000000,124.000000
25%,13.00000,31.000000,102305.000000,30.000000,4.000000,16.000000,1542.000000,28491.500000,2.000000,69.500000,10412.000000,277.000000
50%,25.00000,40.000000,138630.000000,52.000000,8.000000,31.000000,2928.000000,51499.000000,3.300000,76.200000,21695.000000,464.000000
75%,37.00000,51.000000,179048.000000,68.000000,16.000000,41.000000,3863.000000,79662.250000,4.300000,91.700000,38504.000000,775.000000
max,49.00000,65.000000,199639.000000,99.000000,20.000000,50.000000,5000.000000,95805.000000,5.000000,98.900000,48936.000000,999.000000

In [11]:
df.dtypes

id                      int64
age                     int64
salary                  int64
score                   int64
experience_years        int64
projects_completed      int64
customer_count          int64
monthly_sales         float64
rating                float64
attendance_percent    float64
bonus                   int64
department_code         int64
dtype: object

In [12]:
## Handling missing value
df.isnull()

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,True,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,False,False

In [15]:
df.isnull().any(axis=1)  # it means row wise tell where data is missing

0     False
1      True
2     False
3     False
4      True
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21     True
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
dtype: bool

In [18]:
df.isnull().any() #it will tell which column has missing value

id                    False
age                   False
salary                False
score                 False
experience_years      False
projects_completed    False
customer_count        False
monthly_sales          True
rating                False
attendance_percent    False
bonus                 False
department_code       False
dtype: bool

In [ ]:
df.isnull().sum() #is telling which column has how many missing value

id                    0
age                   0
salary                0
score                 0
experience_years      0
projects_completed    0
customer_count        0
monthly_sales         3
rating                0
attendance_percent    0
bonus                 0
department_code       0
dtype: int64

In [22]:
df_filled = df.fillna(0) #replace all the missing value with 0
df_filled

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625
1,2,30,113141,68,18,45,3169,0.0,3.0,64.0,4385,482
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434
4,5,43,50401,44,4,5,5000,0.0,1.8,79.3,40867,136
5,6,43,182840,20,14,30,444,44345.0,4.7,71.2,6367,187
6,7,31,187936,41,7,45,2086,86275.0,1.7,60.3,16880,149
7,8,56,193688,98,11,34,699,45514.0,4.3,61.6,44473,277
8,9,39,103921,94,0,23,2697,62758.0,4.5,93.7,6177,340
9,10,63,180411,53,7,12,4419,94106.0,1.1,98.9,38504,124
10,11,33,170562,33,15,28,1524,2619.0,4.9,94.4,6422,240
11,12,23,161882,24,1,16,1454,47253.0,1.8,71.9,39272,172
12,13,63,124533,90,4,37,2761,26646.0,1.7,76.2,31279,786
13,14,26,37582,22,15,45,2227,62049.0,2.8,87.5,2571,526
14,15,32,81636,97,1,38,1973,20215.0,1.0,96.4,9108,259
15,16,18,148839,23,10,50,555,88195.0,3.3,72.4,35417,421
16,17,22,69408,9,18,49,3628,32850.0,2.6,78.8,20144,234
17,18,51,104776,1,7,2,3757,44061.0,2.1,94.2,17847,623
18,19,60,140886,58,6,11,3147,22960.0,2.0,73.7,47349,681
19,20,46,140708,69,2,33,3643,79705.0,3.0,72.9,6280,357
20,21,40,184741,42,8,31,2299,25185.0,2.2,64.5,40311,807
21,22,20,177588,82,11,32,496,0.0,4.7,93.2,1226,406
22,23,53,175946,52,4,31,3972,62817.0,4.1,78.6,35765,294
23,24,62,183062,0,4,20,3811,43031.0,3.7,71.9,17876,184
24,25,45,88158,43,18,41,1542,8575.0,5.0,63.9,11219,668
25,26,19,173107,48,19,41,4687,75474.0,2.0,86.0,43523,994
26,27,18,32345,19,8,9,2928,28928.0,1.6,74.9,7063,512
27,28,39,187439,66,0,46,3403,64395.0,3.8,64.7,31347,728
28,29,65,117202,29,0,36,2818,72356.0,3.1,66.3,14399,961
29,30,24,37120,37,3,6,2754,94556.0,2.4,65.9,6133,132
30,31,56,129117,29,6,3,4633,92350.0,3.4,87.2,21695,775
31,32,45,74457,57,6,33,4809,8725.0,4.4,94.6,19055,655
32,33,39,142126,43,3,1,1777,18664.0,2.5,69.5,32583,464
33,34,22,136988,99,19,15,4554,10245.0,4.6,71.8,38256,836
34,35,57,128563,53,18,39,2955,17500.0,4.9,91.7,44595,478
35,36,43,96170,30,0,20,88,86342.0,3.8,74.7,28702,809
36,37,23,192699,85,10,37,2382,55745.0,4.5,91.3,48936,548
37,38,51,180824,56,9,46,4150,65846.0,4.5,76.7,1489,910
38,39,38,199639,47,7,17,4973,36625.0,4.6,91.2,14974,294
39,40,25,76058,16,20,29,29,87692.0,1.4,62.3,48251,364
40,41,32,152468,43,16,23,4035,82477.0,3.7,60.4,23567,293
41,42,51,193007,76,7,1,1036,95805.0,1.0,70.2,12357,461
42,43,51,107632,45,16,26,460,34853.0,3.6,89.5,21798,926
43,44,45,102305,59,8,48,3545,81849.0,3.8,76.6,17467,999
44,45,60,179672,61,4,47,3078,39499.0,3.8,98.1,27758,343
45,46,40,95572,59,8,13,3863,10284.0,4.7,63.3,10412,940
46,47,53,120933,74,16,44,3637,45466.0,3.6,94.6,44178,166
47,48,34,113727,20,19,29,2842,79534.0,1.4,62.0,36665,818
48,49,57,138630,53,16,39,1058,73865.0,1.7,96.9,46362,252

In [25]:
## filling missing value with the mean of the column

df['sales_fillNA'] = df['monthly_sales'].fillna(df['monthly_sales'].mean())
df.head(10)

,id,age,salary,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625,28346.000000
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482,53354.804348
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780,94441.000000
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434,73300.000000
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136,53354.804348
5,6,43,182840,20,14,30,444,44345.0,4.7,71.2,6367,187,44345.000000
6,7,31,187936,41,7,45,2086,86275.0,1.7,60.3,16880,149,86275.000000
7,8,56,193688,98,11,34,699,45514.0,4.3,61.6,44473,277,45514.000000
8,9,39,103921,94,0,23,2697,62758.0,4.5,93.7,6177,340,62758.000000
9,10,63,180411,53,7,12,4419,94106.0,1.1,98.9,38504,124,94106.000000

In [30]:
## Renaming columns
df = df.rename(columns={'salary':'CTC'})
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625,28346.000000
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482,53354.804348
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780,94441.000000
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434,73300.000000
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136,53354.804348

In [35]:
##Change dataTypes

df['Value_new'] = df['customer_count'].astype(float)
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625,28346.000000,3980.0
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482,53354.804348,3169.0
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780,94441.000000,4205.0
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434,73300.000000,125.0
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136,53354.804348,5000.0

In [38]:
df['monthly_sales_new'] = df['monthly_sales'].fillna(df['monthly_sales'].mean()).astype(int) ## first assigning missing value then changing its type
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625,28346.000000,3980.0,28346
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482,53354.804348,3169.0,53354
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780,94441.000000,4205.0,94441
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434,73300.000000,125.0,73300
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136,53354.804348,5000.0,53354

In [ ]:
df['Increased CTC']=df['CTC'].apply(lambda x:(x+(x/10))) #created a new column with 10% increased CTC
df.head()

,id,age,CTC,score,experience_years,projects_completed,customer_count,monthly_sales,rating,attendance_percent,bonus,department_code,sales_fillNA,Value_new,monthly_sales_new,Increased CTC
0,1,38,39375,66,5,46,3980,28346.0,3.3,74.0,2003,625,28346.000000,3980.0,28346,43312.5
1,2,30,113141,68,18,45,3169,NaN,3.0,64.0,4385,482,53354.804348,3169.0,53354,124455.1
2,3,38,158227,86,9,7,4205,94441.0,2.0,92.3,18395,780,94441.000000,4205.0,94441,174049.7
3,4,35,179048,71,19,32,125,73300.0,2.1,91.9,41537,434,73300.000000,125.0,73300,196952.8
4,5,43,50401,44,4,5,5000,NaN,1.8,79.3,40867,136,53354.804348,5000.0,53354,55441.1