## Pandas

Its a powerfull data manupulation library, widely used for data analysis and data cleaning. it provides two primary data structures: series and Dataframe. A Series is 1D array like object, while a DataFrame is 2D, size-mutable  and potential heterogeneous tabulor data structure with labeled axes(row and columns).

In [1]:
import pandas as pd

In [3]:
import pandas as pd

data = [1,2,3,4,5]
series = pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [4]:
#series from dict obj
data = {'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a', 'b', 'c']

pd.Series(data, index)

a    10
b    20
c    30
dtype: int64

In [8]:
## DataFrame

## Create a DataFrame from a dict of list

data = {
    'name':['krish', 'piyush', 'john'],
    'age':[25,26,30],
    'city':['banglore', 'bareilly', 'delhi']
}

df = pd.DataFrame(data)
print(df)
print(type(df))

     name  age      city
0   krish   25  banglore
1  piyush   26  bareilly
2    john   30     delhi
<class 'pandas.DataFrame'>

In [9]:
## create a dataframe from a list of dict.

data = [
    {'name':'krish','age':32, 'city' : 'banglore'},
    {'name':'Jogn','age':33, 'city' : 'Pune'},
    {'name':'Raj','age':34, 'city' : 'Lucknow'}
]

df1 = pd.DataFrame(data)
print(df1)

    name  age      city
0  krish   32  banglore
1   Jogn   33      Pune
2    Raj   34   Lucknow

In [ ]:
df3 = pd.read_csv('dummy.csv')
df3.head(6) # top 6
df3.tail(3) # Bottom 3

,column_1,column_2,column_3,column_4,column_5,column_6,column_7,column_8,column_9,column_10,column_11,column_12
97,value_1_98,value_2_98,value_3_98,value_4_98,value_5_98,value_6_98,value_7_98,value_8_98,value_9_98,value_10_98,value_11_98,value_12_98
98,value_1_99,value_2_99,value_3_99,value_4_99,value_5_99,value_6_99,value_7_99,value_8_99,value_9_99,value_10_99,value_11_99,value_12_99
99,value_1_100,value_2_100,value_3_100,value_4_100,value_5_100,value_6_100,value_7_100,value_8_100,value_9_100,value_10_100,value_11_100,value_12_100

In [15]:
## Accessing data from dataframe
df['name']

0     krish
1    piyush
2      john
Name: name, dtype: str

In [19]:
df.loc[0]

name       krish
age           25
city    banglore
Name: 0, dtype: object

In [ ]:
df.iloc[0] ## index location

name       krish
age           25
city    banglore
Name: 0, dtype: object

In [21]:
## Accessing a specified element
df

     name  age      city
0   krish   25  banglore
1  piyush   26  bareilly
2    john   30     delhi

In [22]:
df.at[1,'age']

np.int64(26)

In [23]:
df.at[2,'city']

'delhi'

In [24]:
## Accessing a specified value by iat

df

     name  age      city
0   krish   25  banglore
1  piyush   26  bareilly
2    john   30     delhi

In [25]:
df.iat[2,2]

'delhi'

In [26]:
df

     name  age      city
0   krish   25  banglore
1  piyush   26  bareilly
2    john   30     delhi

In [27]:
## data manupulation with dataFrame
# adding a column
df['salary'] = [50000,60000,70000]

In [28]:
df

     name  age      city  salary
0   krish   25  banglore   50000
1  piyush   26  bareilly   60000
2    john   30     delhi   70000

In [33]:
# remove a column
df.drop('salary', axis=1, inplace=True) # axis=1 means to search in all column and inplace=true means save after making changes

In [38]:
df

     name  age      city
0   krish   27  banglore
1  piyush   28  bareilly
2    john   32     delhi

In [39]:
# add age to a 

df['age'] = df['age'] + 1
df

     name  age      city
0   krish   28  banglore
1  piyush   29  bareilly
2    john   33     delhi

In [40]:
## drop a row
df.drop(0, inplace=True)
df

     name  age      city
1  piyush   29  bareilly
2    john   33     delhi

In [42]:
df3

,column_1,column_2,column_3,column_4,column_5,column_6,column_7,column_8,column_9,column_10,column_11,column_12
0,value_1_1,value_2_1,value_3_1,value_4_1,value_5_1,value_6_1,value_7_1,value_8_1,value_9_1,value_10_1,value_11_1,value_12_1
1,value_1_2,value_2_2,value_3_2,value_4_2,value_5_2,value_6_2,value_7_2,value_8_2,value_9_2,value_10_2,value_11_2,value_12_2
2,value_1_3,value_2_3,value_3_3,value_4_3,value_5_3,value_6_3,value_7_3,value_8_3,value_9_3,value_10_3,value_11_3,value_12_3
3,value_1_4,value_2_4,value_3_4,value_4_4,value_5_4,value_6_4,value_7_4,value_8_4,value_9_4,value_10_4,value_11_4,value_12_4
4,value_1_5,value_2_5,value_3_5,value_4_5,value_5_5,value_6_5,value_7_5,value_8_5,value_9_5,value_10_5,value_11_5,value_12_5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,value_1_96,value_2_96,value_3_96,value_4_96,value_5_96,value_6_96,value_7_96,value_8_96,value_9_96,value_10_96,value_11_96,value_12_96
96,value_1_97,value_2_97,value_3_97,value_4_97,value_5_97,value_6_97,value_7_97,value_8_97,value_9_97,value_10_97,value_11_97,value_12_97
97,value_1_98,value_2_98,value_3_98,value_4_98,value_5_98,value_6_98,value_7_98,value_8_98,value_9_98,value_10_98,value_11_98,value_12_98
98,value_1_99,value_2_99,value_3_99,value_4_99,value_5_99,value_6_99,value_7_99,value_8_99,value_9_99,value_10_99,value_11_99,value_12_99
99,value_1_100,value_2_100,value_3_100,value_4_100,value_5_100,value_6_100,value_7_100,value_8_100,value_9_100,value_10_100,value_11_100,value_12_100

In [43]:
df3.describe()

,column_1,column_2,column_3,column_4,column_5,column_6,column_7,column_8,column_9,column_10,column_11,column_12
count,100,100,100,100,100,100,100,100,100,100,100,100
unique,100,100,100,100,100,100,100,100,100,100,100,100
top,value_1_1,value_2_1,value_3_1,value_4_1,value_5_1,value_6_1,value_7_1,value_8_1,value_9_1,value_10_1,value_11_1,value_12_1
freq,1,1,1,1,1,1,1,1,1,1,1,1

In [45]:
df.describe()

             age
count   2.000000
mean   31.000000
std     2.828427
min    29.000000
25%    30.000000
50%    31.000000
75%    32.000000
max    33.000000